### ISSUE TITLE
change_url doesn't work

### ISSUE THREAD

**Issue by jedie** [YunoHost-Apps/pyinventory_ynh#20]
e.g.: https://github.com/YunoHost-Apps/pyinventory_ynh/issues/16

**Comment by ericgaspar** [comment]
You may need to regenerate in `change_url` this [config file](https://github.com/YunoHost-Apps/pyinventory_ynh/blob/893e53ada2a2b5f71cd650c4277847f210751755/scripts/install#L139-L151) with the `new_domain` and `new_path` variables...
